DEFAULT_CONFIG = """\
# filemindr configuration
# Generated by `filemindr init`
#
# Quick start:
#   filemindr run --dry-run
#   filemindr run
#   filemindr watch --debounce-ms 1000 --stable-ms 2000
#
# Notes:
# - source: directory to scan (and watch).
# - default_target: where unmatched files go.
# - conflict_policy: what to do if destination file already exists:
#     rename | skip | overwrite | trash
#
# Tip (watch mode):
# - In watch mode, filemindr will ignore this YAML file and common temp/lock files.

source: .

# Anything that doesn't match a rule goes here
default_target: ./others

# Default conflict policy applied to all rules unless overridden per-rule
conflict_policy: rename  # rename | skip | overwrite | trash

rules:
  # High priority “specific” rules first
  - name: invoices
    priority: 100
    match:
      # Regex matches file name (case-insensitive)
      regex: "(?i)invoice|receipt|irpf|recibo|nota"
      extensions: ["pdf"]
    action:
      move_to: ./finance/invoices
      # conflict_policy: trash   # optional per-rule override

  - name: old_installers
    priority: 80
    match:
      extensions: ["exe", "msi"]
      older_than_days: 14
    action:
      move_to: ./installers/old

  - name: archives
    priority: 70
    match:
      extensions: ["zip", "rar", "7z", "tar", "gz"]
    action:
      move_to: ./archives

  - name: videos
    priority: 60
    match:
      extensions: ["mp4", "mkv", "mov", "avi", "webm", "m4v"]
    action:
      move_to: ./videos

  - name: audio
    priority: 55
    match:
      extensions: ["mp3", "wav", "m4a", "aac", "flac", "ogg"]
    action:
      move_to: ./audio

  - name: images
    priority: 50
    match:
      extensions: ["jpg", "jpeg", "png", "webp", "gif", "svg"]
    action:
      move_to: ./images

  - name: documents
    priority: 40
    match:
      extensions: ["pdf", "docx", "xlsx", "pptx", "txt", "md"]
    action:
      move_to: ./documents

  - name: code_snippets
    priority: 30
    match:
      extensions: ["py", "js", "ts", "json", "yaml", "yml", "toml"]
    action:
      move_to: ./code

  # Example: keep a "copy" of some files instead of moving them
  # (Useful for "dropbox sync folders", "backup", etc.)
  - name: keep_pdfs_copy
    priority: 10
    match:
      extensions: ["pdf"]
    action:
      copy_to: ./backup/pdfs

# End.
"""