from pathlib import Path
from typer.testing import CliRunner

from filemindr.cli import app
from filemindr.core.config import resolve_config

runner = CliRunner()


def _fake_home(monkeypatch, fake_home: Path) -> None:
    monkeypatch.setattr(Path, "home", lambda: fake_home)


def test_init_local_creates_filemindr_yaml(tmp_path, monkeypatch):
    monkeypatch.chdir(tmp_path)

    result = runner.invoke(app, ["init"])

    assert result.exit_code == 0
    cfg = tmp_path / "filemindr.yaml"
    assert cfg.exists()
    assert "filemindr configuration" in cfg.read_text(encoding="utf-8")


def test_init_global_creates_home_config(tmp_path, monkeypatch):
    fake_home = tmp_path / "home"
    _fake_home(monkeypatch, fake_home)

    result = runner.invoke(app, ["init", "--global"])

    assert result.exit_code == 0
    cfg = fake_home / ".filemindr" / "config.yaml"
    assert cfg.exists()
    assert "Generated by `filemindr init`" in cfg.read_text(encoding="utf-8")


def test_init_refuses_overwrite_without_force(tmp_path, monkeypatch):
    monkeypatch.chdir(tmp_path)
    (tmp_path / "filemindr.yaml").write_text("x", encoding="utf-8")

    result = runner.invoke(app, ["init"])

    assert result.exit_code != 0


def test_init_force_overwrites(tmp_path, monkeypatch):
    monkeypatch.chdir(tmp_path)
    cfg = tmp_path / "filemindr.yaml"
    cfg.write_text("old", encoding="utf-8")

    result = runner.invoke(app, ["init", "--force"])

    assert result.exit_code == 0
    text = cfg.read_text(encoding="utf-8")

    assert text != "old"
    assert text.startswith("# filemindr configuration")
    assert "Generated by `filemindr init`" in text


def test_resolve_config_prefers_local(tmp_path, monkeypatch):
    monkeypatch.chdir(tmp_path)

    local = tmp_path / "filemindr.yaml"
    local.write_text("x", encoding="utf-8")

    assert resolve_config() == local


def test_resolve_config_falls_back_to_home(tmp_path, monkeypatch):
    monkeypatch.chdir(tmp_path)

    fake_home = tmp_path / "home"
    _fake_home(monkeypatch, fake_home)

    cfg = fake_home / ".filemindr" / "config.yaml"
    cfg.parent.mkdir(parents=True)
    cfg.write_text("x", encoding="utf-8")

    assert resolve_config() == cfg.resolve()


def test_resolve_config_raises_if_missing(tmp_path, monkeypatch):
    monkeypatch.chdir(tmp_path)

    fake_home = tmp_path / "home"
    _fake_home(monkeypatch, fake_home)

    assert not (tmp_path / "filemindr.yaml").exists()
    assert not (fake_home / ".filemindr" / "config.yaml").exists()

    try:
        resolve_config()
    except FileNotFoundError:
        pass
    else:
        assert False
